---
apiVersion: v1
kind: Namespace
metadata:
  name: felfel
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: felfel
type: Opaque
data:
  redis-password: SGVsbG8xMjM=

