version: "3"
services:
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  application:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: ../
    image: fabrinator/task-work:latest
    container_name: task-work
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: "0"

